name: Update DateTime in Dockerfile

on:
  schedule:
    - cron: '*/5 * * * *'  # 每隔5分钟触发

jobs:
  update_datetime:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Update DateTime
      run: |
        # 获取当前北京时间并格式化为 "YYYY-MM-DD HH:MM:SS" 格式
        datetime=$(TZ="Asia/Shanghai" date +\%F\ %T)
        
        # 在 Dockerfile 中插入时间注释
        sed -i "1s/^/# Updated on: $datetime\n/" Dockerfile
        
        # 提交并推送更改到 GitHub
        git config --global user.name "GitHub Actions"
        git config --global user.email "actions@github.com"
        git add Dockerfile
        git commit -m "Update DateTime in Dockerfile"
        git push origin main
